volumes:
  static:
services:
  code:
    build: .
    ports:
      - "3000:80"
    volumes:
      - static:/usr/src/app/build/
  server:
    image: "nginx:stable"
    ports:
      - "3600:80"
    volumes:
      - static:/var/www
      - ./deploy/default.conf:/etc/nginx/conf.d/default.conf
